### ISSUE TITLE
【Electron】移动/重命名/新建文件夹失败

### ISSUE THREAD

**Issue by meetqy** [meetqy/rao-pics#456]
```
PrismaClientKnownRequestError: 
Invalid `prisma.image.delete()` invocation in
/Users/meetqy/Desktop/me/electron-vite/apps/electron/out/main/index.js:8746:33

  8743   return prisma.image.delete({ where: { id } });
  8744 }
  8745 if (path3) {
→ 8746   return prisma.image.delete(
An operation failed because it depends on one or more records that were required but not found. Record to delete does not exist.
    at Cn.handleRequestError (/Users/meetqy/Desktop/me/electron-vite/node_modules/@prisma/client/runtime/library.js:123:6817)
    at Cn.handleAndLogRequestError (/Users/meetqy/Desktop/me/electron-vite/node_modules/@prisma/client/runtime/library.js:123:6206)
    at Cn.request (/Users/meetqy/Desktop/me/electron-vite/node_modules/@prisma/client/runtime/library.js:123:5926)
    at async l (/Users/meetqy/Desktop/me/electron-vite/node_modules/@prisma/client/runtime/library.js:128:9968)
    at async resolveMiddleware (/Users/meetqy/Desktop/me/electron-vite/apps/electron/out/main/index.js:6946:22)
    at async callRecursive (/Users/meetqy/Desktop/me/electron-vite/apps/electron/out/main/index.js:6979:25)
    at async callRecursive (/Users/meetqy/Desktop/me/electron-vite/apps/electron/out/main/index.js:6979:25)
    at async resolve3 (/Users/meetqy/Desktop/me/electron-vite/apps/electron/out/main/index.js:7008:20)
    at async deleteImage (/Users/meetqy/Desktop/me/electron-vite/apps/electron/out/main/index.js:9210:3)
    at async syncImage (/Users/meetqy/Desktop/me/electron-vite/apps/electron/out/main/index.js:9271:11)
```

**Comment by meetqy** [comment]
未对保存文件夹数据的文件进行监听

**Comment by meetqy** [comment]
文件夹同步逻辑：

1. 读取 metadata.json 处理 folder 转为一维数组
2. metadata folder 与 db.sqlite folder 做对比
3. 找出 metadata folder 中删除移除的 folder 并删除
4. 新增的进行创建并链接素材
